image: jerson/react-native:android-28

before_script:
  - cp -f src/Config.tsx-dist src/Config.tsx
  - cp -f android/gradle.properties-dist android/gradle.properties
  - sed -i'' -e "s/YOUR_STORE_PASSWORD/${APP_STORE_PASSWORD}/g" android/gradle.properties
  - sed -i'' -e "s/YOUR_KEY_PASSWORD/${APP_KEY_PASSWORD}/g" android/gradle.properties
  - sed -i'' -e "s/YOUR_KEY_ALIAS/${APP_KEY_ALIAS}/g" android/gradle.properties
  - base64 --decode $APP_KEY_STORE > android/app/app.keystore
  - base64 --decode $APP_KEY_STORE > android/wear/app.keystore

stages:
  - test
  - build
  - deploy

lint:
  stage: test
  script:
    - make deps
    - make lint
  when: always

android_build_release:
  stage: build
  script:
    - make deps
    - make android-build-release
  when: manual
  artifacts:
    paths:
      - app/build/outputs/apk/release
    expire_in: 1 week

ios_build_release:
  stage: build
  tags:
    - osx
  script:
    - make deps
    - make ios-build-release
  when: manual
  #artifacts:
  #  paths:
  #    - app/build/outputs/apk/release
  #  expire_in: 1 week

android_deploy_release_beta:
  stage: deploy
  script:
    - make deps
    - base64 --decode $GOOGLE_PLAY_SETTINGS > android/fastlane/google-play.json
    - make android-deploy-release-beta
  when: manual

android_deploy_release:
  stage: deploy
  script:
    - make deps
    - base64 --decode $GOOGLE_PLAY_SETTINGS > android/fastlane/google-play.json
    - make android-deploy-release
  when: manual

ios_deploy_release_beta:
  stage: deploy
  tags:
    - osx
  script:
    - make deps
    - brew cask install fastlane
    - make ios-deploy-release-beta
  when: manual

ios_deploy_release:
  stage: deploy
  tags:
    - osx
  script:
    - make deps
    - brew cask install fastlane
    - make ios-deploy-release
  when: manual
