include:
  - local: .gitlab-ci/android.yml
  - local: .gitlab-ci/ios.yml

stages:
  - test
  - build
  - deploy
  - release

lint:
  image: jerson/node:10.16
  stage: test
  script:
    - cp -f src/Config.tsx-dist src/Config.tsx
    - make deps
    - make lint
  when: always

test:
  image: jerson/node:10.16
  stage: test
  script:
    - cp -f src/Config.tsx-dist src/Config.tsx
    - make deps
    - make test
  when: always
  coverage: '/^All files\s+\|\s+\d+\.*\d*\s+\|\s*(\d+\.*\d*)/'
