image: jerson/react-native:android-28

before_script:
  - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
  - cp -f src/Config.tsx-dist src/Config.tsx
  - cp -f android/gradle.properties-dist android/gradle.properties
  - sed -i "s/YOUR_STORE_PASSWORD/${APP_STORE_PASSWORD}/g" android/gradle.properties
  - sed -i "s/YOUR_KEY_PASSWORD/${APP_KEY_PASSWORD}/g" android/gradle.properties
  - sed -i "s/YOUR_KEY_ALIAS/${APP_KEY_ALIAS}/g" android/gradle.properties
  - base64 --decode $APP_KEY_STORE > android/app/app.keystore

stages:
- test
- build

test:
  stage: test
  script:
  - apt-get update
  - apt-get install sonar-scanner -y
  - sonar-scanner -Dsonar.host.url=$SONAR_SERVER -Dsonar.login=$SONAR_TOKEN
  - make deps
  - make test
  when: always

lint:
  stage: test
  script:
  - make deps
  - make lint
  when: always

release:
  stage: build
  script:
  - make deps
  - make build-android-release
  when: manual
  artifacts:
    paths:
    - app/build/outputs/apk/release
    expire_in: 1 week

beta:
  stage: build
  script:
  - make deps
  - make build-android-beta
  when: manual
  artifacts:
    paths:
    - app/build/outputs/apk/releaseBeta
    expire_in: 1 week