image: jerson/react-native:android-28

before_script:
  - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
  - cp -f src/Config.tsx-dist src/Config.tsx
  - cp -f android/gradle.properties-dist android/gradle.properties
  - sed -i "s/YOUR_STORE_PASSWORD/${APP_STORE_PASSWORD}/g" android/gradle.properties
  - sed -i "s/YOUR_KEY_PASSWORD/${APP_KEY_PASSWORD}/g" android/gradle.properties
  - sed -i "s/YOUR_KEY_ALIAS/${APP_KEY_ALIAS}/g" android/gradle.properties
  - base64 --decode $APP_KEY_STORE > android/app/app.keystore
  - base64 --decode $APP_KEY_STORE > android/wear/app.keystore

stages:
- test
- build
- deploy

test:
  stage: test
  script:
  - make deps
  - make test
  when: always
  
lint:
  stage: test
  script:
  - make deps
  - make lint
  when: always

build_beta:
  stage: build
  script:
  - make deps
  - make android-build-beta
  when: manual
  artifacts:
    paths:
    - app/build/outputs/apk/releaseBeta
    expire_in: 1 week

build_release:
  stage: build
  script:
  - make deps
  - make android-build-release
  when: manual
  artifacts:
    paths:
    - app/build/outputs/apk/release
    expire_in: 1 week

deploy_release_beta:
  stage: deploy
  script:
  - make deps
  - apt-get update && apt-get install -y ruby ruby-dev
  - gem install fastlane -NV
  - base64 --decode $GOOGLE_PLAY_SETTINGS > android/fastlane/google-play.json
  - make android-deploy-release-beta
  when: manual

deploy_release:
  stage: deploy
  script:
  - make deps
  - apt-get update && apt-get install -y ruby ruby-dev
  - gem install fastlane -NV
  - base64 --decode $GOOGLE_PLAY_SETTINGS > android/fastlane/google-play.json
  - make android-deploy-release
  when: manual
