stages:
  - test
  - build
  - deploy
  - release

lint:
  image: jerson/node:10.16
  stage: test
  script:
    - cp -f src/Config.tsx-dist src/Config.tsx
    - make deps
    - make lint
  when: always

test:
  image: jerson/node:10.16
  stage: test
  script:
    - cp -f src/Config.tsx-dist src/Config.tsx
    - make deps
    - make test
  when: always
  coverage: '/^All files\s+\|\s+\d+\.*\d*\s+\|\s*(\d+\.*\d*)/'

android_build_release:
  image: jerson/react-native:android-28
  stage: build
  script:
    - cp -f src/Config.tsx-dist src/Config.tsx
    - cp -f android/gradle.properties-dist android/gradle.properties
    - sed -i'' -e "s/YOUR_STORE_PASSWORD/${APP_STORE_PASSWORD}/g" android/gradle.properties
    - sed -i'' -e "s/YOUR_KEY_PASSWORD/${APP_KEY_PASSWORD}/g" android/gradle.properties
    - sed -i'' -e "s/YOUR_KEY_ALIAS/${APP_KEY_ALIAS}/g" android/gradle.properties
    - sed -i'' -e "s/YOUR_VERSION_CODE/${CI_JOB_ID}/g" android/gradle.properties
    - base64 --decode $APP_KEY_STORE > android/app/app.keystore
    - base64 --decode $APP_KEY_STORE > android/wear/app.keystore
    - make deps
    - make android-build-release
  only:
    - develop
    - master
  artifacts:
    paths:
      - android/app/build/outputs/bundle/release
    expire_in: 1 week
  when: always
  dependencies:
    - lint
    - test
  allow_failure: false
  interruptible: true

ios_build_release:
  stage: build
  tags:
    - osx
  script:
    - cp -f src/Config.tsx-dist src/Config.tsx
    - base64 --decode $KEYCHAIN > ios/xcode.keychain
    - make deps
    - make ios-build-release
  only:
    - develop
    - master
  artifacts:
    paths:
      - ios/ipa
    expire_in: 1 week
  dependencies:
    - lint
    - test
  when: always
  allow_failure: false
  interruptible: true

android_deploy_release_beta:
  image: jerson/fastlane:2
  stage: deploy
  script:
    - base64 --decode $GOOGLE_PLAY_SETTINGS > android/fastlane/google-play.json
    - make android-deploy-release-beta
  only:
    - develop
  when: manual
  dependencies:
    - android_build_release

ios_deploy_release_beta:
  image: jerson/fastlane:2
  stage: deploy
  script:
    - make ios-deploy-release-beta
  only:
    - develop
  when: manual
  dependencies:
    - ios_build_release

android_deploy_release:
  image: jerson/fastlane:2
  stage: release
  script:
    - base64 --decode $GOOGLE_PLAY_SETTINGS > android/fastlane/google-play.json
    - make android-deploy-release
  only:
    - master
  when: manual
  dependencies:
    - android_build_release
  environment:
    name: production

ios_deploy_release:
  image: jerson/fastlane:2
  stage: release
  script:
    - make ios-deploy-release
  only:
    - master
  when: manual
  dependencies:
    - ios_build_release
  environment:
    name: production
