image: jerson/react-native:android-28

variables:
  SONAR_VERSION: "4.0.0.1744"

before_script:
  - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
  - cp -f src/Config.tsx-dist src/Config.tsx
  - cp -f android/gradle.properties-dist android/gradle.properties
  - sed -i "s/YOUR_STORE_PASSWORD/${APP_STORE_PASSWORD}/g" android/gradle.properties
  - sed -i "s/YOUR_KEY_PASSWORD/${APP_KEY_PASSWORD}/g" android/gradle.properties
  - sed -i "s/YOUR_KEY_ALIAS/${APP_KEY_ALIAS}/g" android/gradle.properties
  - base64 --decode $APP_KEY_STORE > android/app/app.keystore
  - base64 --decode $APP_KEY_STORE > android/wear/app.keystore

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - make deps
    - make test
    - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_VERSION-linux.zip -O sonar.zip; unzip sonar.zip; rm sonar.zip
    - ./sonar-scanner-$SONAR_VERSION-linux/bin/sonar-scanner -Dsonar.host.url=$SONAR_SERVER -Dsonar.login=$SONAR_TOKEN
  when: always

lint:
  stage: test
  tags:
    - osx
  script:
    - make deps
    - make lint
  when: always

android_build_release:
  stage: build
  script:
    - make deps
    - make android-build-release
  when: manual
  artifacts:
    paths:
      - app/build/outputs/apk/release
    expire_in: 1 week

ios_build_release:
  stage: build
  script:
    - make deps
    - make ios-build-release
  when: manual
  #artifacts:
  #  paths:
  #    - app/build/outputs/apk/release
  #  expire_in: 1 week

android_deploy_release_beta:
  stage: deploy
  script:
    - make deps
    - apt-get update && apt-get install -y ruby ruby-dev
    - gem install fastlane -NV
    - base64 --decode $GOOGLE_PLAY_SETTINGS > android/fastlane/google-play.json
    - make android-deploy-release-beta
  when: manual

android_deploy_release:
  stage: deploy
  script:
    - make deps
    - apt-get update && apt-get install -y ruby ruby-dev
    - gem install fastlane -NV
    - base64 --decode $GOOGLE_PLAY_SETTINGS > android/fastlane/google-play.json
    - make android-deploy-release
  when: manual

ios_deploy_release_beta:
  stage: deploy
  tags:
    - osx
  script:
    - make deps
    - brew cask install fastlane
    - make ios-deploy-release-beta
  when: manual

ios_deploy_release:
  stage: deploy
  tags:
    - osx
  script:
    - make deps
    - brew cask install fastlane
    - make ios-deploy-release
  when: manual
