.build-android:
  image: jerson/react-native:android-28
  script:
    - cp -f src/Config.tsx-dist src/Config.tsx
    - cp -f android/gradle.properties-dist android/gradle.properties
    - sed -i'' -e "s/YOUR_STORE_PASSWORD/${APP_STORE_PASSWORD}/g" android/gradle.properties
    - sed -i'' -e "s/YOUR_KEY_PASSWORD/${APP_KEY_PASSWORD}/g" android/gradle.properties
    - sed -i'' -e "s/YOUR_KEY_ALIAS/${APP_KEY_ALIAS}/g" android/gradle.properties
    - sed -i'' -e "s/YOUR_VERSION_CODE/${CI_JOB_ID}/g" android/gradle.properties
    - base64 -d $APP_KEY_STORE > android/app/app.keystore
    - base64 -d $APP_KEY_STORE > android/wear/app.keystore
    - make deps
    - make android-build-release
  artifacts:
    paths:
      - android/app/build/outputs/bundle/release
    expire_in: 1 week
  dependencies:
    - lint

android_codepush_release:
  image: jerson/node:10.16
  stage: build
  script:
    - cp -f src/Config.tsx-dist src/Config.tsx
    - cp -f android/gradle.properties-dist android/gradle.properties
    - npm install -g appcenter-cli
    - appcenter login --token $APPCENTER_ACCESSKEY
    - make deps
    - npm run codepush:android:production
  when: manual
  dependencies:
    - test

android_build_release_develop:
  extends: .build-android
  stage: build
  when: manual
  only:
    - develop

android_build_release_master:
  extends: .build-android
  stage: build
  when: always
  only:
    - master

android_deploy_release_beta:
  image: jerson/fastlane:2
  stage: deploy
  script:
    - base64 -d $GOOGLE_PLAY_SETTINGS > android/fastlane/google-play.json
    - make android-deploy-release-beta
  only:
    - develop
  when: manual
  dependencies:
    - android_build_release_develop

android_deploy_release:
  image: jerson/fastlane:2
  stage: deploy
  script:
    - base64 -d $GOOGLE_PLAY_SETTINGS > android/fastlane/google-play.json
    - make android-deploy-release
  only:
    - master
  when: manual
  environment:
    name: production
  dependencies:
    - android_build_release_master
