.build-ios:
  tags:
    - osx
  script:
    - cp -f src/Config.tsx-dist src/Config.tsx
    - base64 --decode $KEYCHAIN > ios/xcode.keychain
    - make deps
    - make ios-build-release
  artifacts:
    paths:
      - ios/ipa
    expire_in: 1 week
  dependencies:
    - lint
  allow_failure: false

ios_codepush_release:
  image: jerson/node:10.16
  stage: build
  script:
    - cp -f src/Config.tsx-dist src/Config.tsx
    - npm install -g appcenter-cli
    - appcenter login --accessKey $CODEPUSH_ACCESSKEY
    - make deps
    - npm run codepush:ios:production
  when: manual
  dependencies:
    - test

ios_build_release_develop:
  extends: .build-ios
  stage: build
  when: manual
  only:
    - develop

ios_build_release_master:
  extends: .build-ios
  stage: build
  when: always
  only:
    - master

ios_deploy_release_beta:
  image: jerson/fastlane:2
  stage: deploy
  script:
    - make ios-deploy-release-beta
  only:
    - develop
  when: manual
  dependencies:
    - ios_build_release_develop

ios_deploy_release:
  image: jerson/fastlane:2
  stage: deploy
  script:
    - make ios-deploy-release
  only:
    - master
  when: manual
  environment:
    name: production
  dependencies:
    - ios_build_release_master
