// Objective-C API for talking to safebox.jerson.dev/api/mobile Go package.
//   gobind -lang=objc safebox.jerson.dev/api/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Safebox_H__
#define __Safebox_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class SafeboxAccount;
@class SafeboxAccountResponse;
@class SafeboxAccountSingle;
@class SafeboxAccountsResponse;
@class SafeboxAddAccountResponse;
@class SafeboxAuthResponse;
@class SafeboxKeyPairResponse;
@class SafeboxLogoutResponse;
@class SafeboxSafeBox;
@class SafeboxSession;

/**
 * Account ...
 */
@interface SafeboxAccount : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull label;
@property (nonatomic) NSString* _Nonnull username;
@property (nonatomic) NSString* _Nonnull password;
@property (nonatomic) NSString* _Nonnull hint;
@end

/**
 * AccountResponse ...
 */
@interface SafeboxAccountResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) SafeboxAccount* _Nullable account;
@end

/**
 * AccountSingle ...
 */
@interface SafeboxAccountSingle : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t id_;
@property (nonatomic) NSString* _Nonnull label;
@property (nonatomic) NSString* _Nonnull username;
@property (nonatomic) NSString* _Nonnull hint;
@end

/**
 * AccountsResponse ...
 */
@interface SafeboxAccountsResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field AccountsResponse.Accounts with unsupported type: []*safebox.jerson.dev/api/mobile.AccountSingle

@end

/**
 * AddAccountResponse ...
 */
@interface SafeboxAddAccountResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t id_;
@end

/**
 * AuthResponse ...
 */
@interface SafeboxAuthResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull accessToken;
@property (nonatomic) NSString* _Nonnull dateExpire;
@property (nonatomic) NSString* _Nonnull date;
@property (nonatomic) SafeboxKeyPairResponse* _Nullable keyPair;
@end

/**
 * KeyPairResponse ...
 */
@interface SafeboxKeyPairResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull publicKey;
@property (nonatomic) NSString* _Nonnull privateKey;
@end

/**
 * LogoutResponse ...
 */
@interface SafeboxLogoutResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

/**
 * SafeBox ...
 */
@interface SafeboxSafeBox : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewSafeBox ...
 */
- (nullable instancetype)init:(NSString* _Nullable)server;
@property (nonatomic) NSString* _Nonnull server;
@property (nonatomic) SafeboxSession* _Nullable session;
- (SafeboxAddAccountResponse* _Nullable)addAccount:(NSString* _Nullable)label hint:(NSString* _Nullable)hint username:(NSString* _Nullable)username password:(NSString* _Nullable)password error:(NSError* _Nullable* _Nullable)error;
- (SafeboxAccountResponse* _Nullable)getAccount:(int64_t)id_ error:(NSError* _Nullable* _Nullable)error;
- (SafeboxAccountsResponse* _Nullable)getAccounts:(NSError* _Nullable* _Nullable)error;
- (SafeboxAuthResponse* _Nullable)login:(NSString* _Nullable)username password:(NSString* _Nullable)password error:(NSError* _Nullable* _Nullable)error;
- (SafeboxAuthResponse* _Nullable)loginDevice:(NSString* _Nullable)publicKey error:(NSError* _Nullable* _Nullable)error;
- (SafeboxLogoutResponse* _Nullable)logout:(NSError* _Nullable* _Nullable)error;
- (SafeboxAuthResponse* _Nullable)register:(NSString* _Nullable)username password:(NSString* _Nullable)password error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Session ...
 */
@interface SafeboxSession : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * SetAccessToken ...
 */
- (void)setAccessToken:(NSString* _Nullable)token;
@end

/**
 * NewSafeBox ...
 */
FOUNDATION_EXPORT SafeboxSafeBox* _Nullable SafeboxNewSafeBox(NSString* _Nullable server);

#endif
