// Objective-C API for talking to safebox.jerson.dev/api/mobile Go package.
//   gobind -lang=objc safebox.jerson.dev/api/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Safebox_H__
#define __Safebox_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class SafeboxAccount;
@class SafeboxAccountResponse;
@class SafeboxAccountSingle;
@class SafeboxAccountSingleCollection;
@class SafeboxAddAccountResponse;
@class SafeboxAuthResponse;
@class SafeboxKeyPairResponse;
@class SafeboxLogoutResponse;
@class SafeboxSafeBox;
@class SafeboxSession;

/**
 * Account ...
 */
@interface SafeboxAccount : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull label;
@property (nonatomic) NSString* _Nonnull username;
@property (nonatomic) NSString* _Nonnull password;
@property (nonatomic) NSString* _Nonnull hint;
@end

/**
 * AccountResponse ...
 */
@interface SafeboxAccountResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) SafeboxAccount* _Nullable account;
@end

/**
 * AccountSingle ...
 */
@interface SafeboxAccountSingle : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t id_;
@property (nonatomic) NSString* _Nonnull label;
@property (nonatomic) NSString* _Nonnull username;
@property (nonatomic) NSString* _Nonnull hint;
/**
 * Equal ...
 */
- (BOOL)equal:(SafeboxAccountSingle* _Nullable)s2;
@end

/**
 * AccountSingleCollection ...
 */
@interface SafeboxAccountSingleCollection : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
// skipped constructor AccountSingleCollection.NewAccountSingleCollection with unsupported parameter or return types

/**
 * At ...
 */
- (SafeboxAccountSingle* _Nullable)at:(long)i;
/**
 * Clear ...
 */
- (void)clear;
/**
 * Clone ...
 */
- (SafeboxAccountSingleCollection* _Nullable)clone;
/**
 * Copy ...
 */
- (void)copy:(SafeboxAccountSingleCollection* _Nullable)rhs;
/**
 * Count ...
 */
- (long)count;
/**
 * Equal ...
 */
- (BOOL)equal:(SafeboxAccountSingleCollection* _Nullable)rhs;
/**
 * Index ...
 */
- (long)index:(SafeboxAccountSingle* _Nullable)rhs;
/**
 * Insert ...
 */
- (void)insert:(long)i n:(SafeboxAccountSingle* _Nullable)n;
/**
 * MarshalJSON ...
 */
- (NSData* _Nullable)marshalJSON:(NSError* _Nullable* _Nullable)error;
/**
 * Remove ...
 */
- (void)remove:(long)i;
/**
 * UnmarshalJSON ...
 */
- (BOOL)unmarshalJSON:(NSData* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * AddAccountResponse ...
 */
@interface SafeboxAddAccountResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t id_;
@end

/**
 * AuthResponse ...
 */
@interface SafeboxAuthResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull accessToken;
@property (nonatomic) NSString* _Nonnull dateExpire;
@property (nonatomic) NSString* _Nonnull date;
@property (nonatomic) SafeboxKeyPairResponse* _Nullable keyPair;
@end

/**
 * KeyPairResponse ...
 */
@interface SafeboxKeyPairResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull publicKey;
@property (nonatomic) NSString* _Nonnull privateKey;
@end

/**
 * LogoutResponse ...
 */
@interface SafeboxLogoutResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

/**
 * SafeBox ...
 */
@interface SafeboxSafeBox : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewSafeBox ...
 */
- (nullable instancetype)init:(NSString* _Nullable)server;
@property (nonatomic) NSString* _Nonnull server;
@property (nonatomic) SafeboxSession* _Nullable session;
- (SafeboxAddAccountResponse* _Nullable)addAccount:(NSString* _Nullable)label hint:(NSString* _Nullable)hint username:(NSString* _Nullable)username password:(NSString* _Nullable)password error:(NSError* _Nullable* _Nullable)error;
- (SafeboxAccountResponse* _Nullable)getAccount:(int64_t)id_ error:(NSError* _Nullable* _Nullable)error;
- (SafeboxAccountSingleCollection* _Nullable)getAccounts:(NSError* _Nullable* _Nullable)error;
- (SafeboxAuthResponse* _Nullable)login:(NSString* _Nullable)username password:(NSString* _Nullable)password error:(NSError* _Nullable* _Nullable)error;
- (SafeboxAuthResponse* _Nullable)loginDevice:(NSString* _Nullable)publicKey error:(NSError* _Nullable* _Nullable)error;
- (SafeboxAuthResponse* _Nullable)loginDevicePremium:(NSString* _Nullable)publicKey error:(NSError* _Nullable* _Nullable)error;
- (SafeboxAuthResponse* _Nullable)loginPremium:(NSString* _Nullable)username password:(NSString* _Nullable)password error:(NSError* _Nullable* _Nullable)error;
- (SafeboxLogoutResponse* _Nullable)logout:(NSError* _Nullable* _Nullable)error;
- (SafeboxAuthResponse* _Nullable)refreshToken:(NSError* _Nullable* _Nullable)error;
- (SafeboxAuthResponse* _Nullable)register:(NSString* _Nullable)username password:(NSString* _Nullable)password error:(NSError* _Nullable* _Nullable)error;
/**
 * SetSessionPassword ...
 */
- (void)setSessionPassword:(NSString* _Nullable)password;
/**
 * SetSessionResponse ...
 */
- (void)setSessionResponse:(SafeboxAuthResponse* _Nullable)response;
@end

/**
 * Session ...
 */
@interface SafeboxSession : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

// skipped function NewAccountSingleCollection with unsupported parameter or return types


/**
 * NewSafeBox ...
 */
FOUNDATION_EXPORT SafeboxSafeBox* _Nullable SafeboxNewSafeBox(NSString* _Nullable server);

#endif
