
// Objective-C API for talking to the following Go packages
//
//	safebox.jerson.dev/api/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Safebox_FRAMEWORK_H__
#define __Safebox_FRAMEWORK_H__

#include "Safebox.objc.h"
#include "Universe.objc.h"

#endif
