
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  desc "Build Beta IPA"
  lane :build_beta do
    cocoapods
    unlock_keychain(
      path: "xcode.keychain",
      password: ""
    )
    # esto genera otro, y ya esta en el keychain
    # get_certificates        
    get_provisioning_profile 
    increment_build_number(build_number: ENV['CI_JOB_ID'])
    gym(
      scheme: "SafeBox (Beta)",
      output_directory: "ipa"
    ) 
  end

  desc "Build Release IPA"
  lane :build_release do
    cocoapods
    unlock_keychain(
      path: "xcode.keychain",
      password: ""
    )
    # esto genera otro, y ya esta en el keychain
    # get_certificates         
    get_provisioning_profile 
    increment_build_number(build_number: ENV['CI_JOB_ID'])
    gym(
      scheme: "SafeBox",
      output_directory: "ipa"
    ) 
  end

  desc "Deploy a new version to the Apple Store - Release channel"
  lane :deploy_release do
    deliver(force: true)
  end

  desc "Deploy a new version to the Apple Store - Beta channel"
  lane :deploy_release_beta do
    pilot
  end

end
