name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  android:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: android-actions/setup-android@v2
      - name: Install Android Platform
        run: |
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-29"
          sdkmanager "build-tools;29.0.2"
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21d
      - name: Add secrets
        run: |
          base64 -d $GOOGLE_PLAY_SECRET > android/fastlane/google-play.json
        env:
          GOOGLE_PLAY_SECRET: ${{ secrets.GOOGLE_PLAY_SECRET }}
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - uses: maierj/fastlane-action@v2.0.1
        with:
          subdirectory: 'android'
          lane: 'build_release'
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: SafeBox_$tag.aab
          file: android/app/build/outputs/bundle/release/app.aab
          tag: ${{ github.ref }}
          overwrite: true
      - uses: maierj/fastlane-action@v2.0.1
        with:
          subdirectory: 'android'
          lane: 'deploy_release_internal'

  ios:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - uses: maierj/fastlane-action@v2.0.1
        with:
          subdirectory: 'ios'
          lane: 'build_release'
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: SafeBox_$tag.ipa
          file: ios/ipa/SafeBox.ipa
          tag: ${{ github.ref }}
          overwrite: true
