name: iOS Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version Overwrite
        required: false
  push:
    tags:
      - "v*"
      
env:
  VERSION: ${{ github.event.inputs.version || (startsWith(github.ref, 'refs/tags/') && github.ref || '') }}

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Config
        run: |
          cp -f src/Config.tsx-dist src/Config.tsx
      - name: Add secrets
        run: |
          echo $KEYCHAIN | base64 -d > ios/xcode.keychain
        env:
          KEYCHAIN: ${{ secrets.KEYCHAIN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache 
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Deps
        run: make deps
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - uses: maierj/fastlane-action@v2.0.1
        with:
          subdirectory: 'ios'
          lane: 'ios build_release'
      - if: ${{ env.VERSION!='' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: SafeBox_ios_$tag.ipa
          file: ios/ipa/SafeBox.ipa
          tag: ${{ env.VERSION }}
          overwrite: true
      - if: ${{ env.VERSION=='' }}
        uses: actions/upload-artifact@v2
        with:
          name: SafeBox_ios
          path: ios/ipa/SafeBox.ipa
      - uses: maierj/fastlane-action@v2.0.1
        with:
          subdirectory: 'android'
          lane: 'ios deploy_release_beta'

